### ISSUE TITLE
Native JS camera handling?

### ISSUE THREAD

**Issue by stuartpb** [Shinao/SmartMirror#1]
Wouldn't it be possible to do the OpenCV stuff using getUserMedia and something like [tracking.js](https://trackingjs.com/) (or even just the [OpenCV bindings for Node](https://github.com/peterbraden/node-opencv))?

**Comment by Shinao** [comment]
Before doing this I checked both of this possibilities.
The demo of tracking.js wasn't working with my camera and there is a lot of cool features that OpenCV only has, I wasn't sold on this lib.
As for node-opencv, that was my first approach but couldn't even make it past the install, there are a few open issues on this subject without any reply from the author and I didn't want to debug it when it was already working in Python. Nevertheless if you can install it without problem and want to make your own gesture detection or rewrite it, go for it  :+1:

**Comment by pankajii** [comment]
Hey buddy! 
     How can i add my url like other website  movie,music and news .
When i was add my url they didn't work.

**Comment by Shinao** [comment]
I don't understand your question. What url, where and what for ?
Also it does not seem to have something to do with the current issue. Why not create a new one ?

**Comment by pankajii** [comment]
I want to change Below url to my local movie site but it doesn't work.
When i put my site url here it doesn't show any result.

config.widget.cinema.url =
'http://www.allocine.fr/seance/salle_gen_csalle=C0159.html';
config.widget.cinema.refreshRateInMinutes = 60;

**Comment by Shinao** [comment]
It does not display the website, it parses the movies on the page and display it. If you want to use it on another one you have to create your own extension/parsing method for it.

**Comment by pankajii** [comment]
Which algorithm  you have use in this smart mirror project.
