### ISSUE TITLE
problem in tracking of palm and gesture 

### ISSUE THREAD

**Issue by phoneix1221** [Shinao/SmartMirror#10]
my skin tone is not too fair . its hard to make the detection to work with the environment i have white wall and sometimes it detects palm but lost tracking of it .it is  not able to detect the thumbup move left up down and right and i dont know why there is huge nice in background if u can hep me with hsv values  and hand setup it will be great help .

**Comment by Shinao** [comment]
Sorry for the late answer.
Honestly if your skin tone matches your background it's going to be a bit hard for the hand to be recognized, though you can fine tune a bit in the settings to increment the HSV values slower so that it differentiate between the two.

**Comment by manuel0007** [comment]
Hi, I would appriciate your help.
I tried to run the test.py file but i get the following error:

    __,contours,_ = cv2.findContours(search_hand_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
     ValueError: not enough values to unpack (expected 3, got 2)_

After i tried to change the 'Contours' (see below changes) i received the following error:

      _File "/home/pi/Downloads/SmartMirror-master/Motion/gesture.py", line 44, in CheckForPalm
      for i in range(self.defects.shape[1]):
      AttributeError: 'NoneType' object has no attribute 'shape'_

Changes '**Contours**':
------------------------------------------------------


        def InitFromMask(self, search_hand_mask):
        # Check each contours
        contours, _= cv2.findContours(search_hand_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

        for contour in contours:
            if self.InitFromContour(contour):
                return True
        return False

    def InitFromMaskAndPosition(self, search_hand_mask, nearestFromX, nearestfromY):
        # Check each contours
        contours, _= cv2.findContours(search_hand_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
        distanceContours = []`
