### ISSUE TITLE
My video screen is not smooth

### ISSUE THREAD

**Issue by Zavianx** [Shinao/SmartMirror#11]
I'm using rasipberry3B (1G memory) ,but i find my picture is not smooth can you tell me why

**Comment by Shinao** [comment]
If you are talking about the framerate then it depends on how high your resolution is mainly, you could try to reduce it.

**Comment by Zavianx** [comment]
Hey i am glad you reply to me. But I have another question .When i using you code,my palm can't be detected.And I don't know what's the meaning for INC S DEC S or MAX VCan you tell me what i should change for these parameters.




------------------ 原始邮件 ------------------
发件人: "Raphael Monnerat"<notifications@github.com>; 
发送时间: 2019年9月5日(星期四) 晚上9:21
收件人: "Shinao/SmartMirror"<SmartMirror@noreply.github.com>; 
抄送: "754990052"<754990052@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [Shinao/SmartMirror] My video screen is not smooth (#11)




If you are talking about the framerate then it depends on how high your resolution is mainly, you could try to reduce it.

**Comment by Shinao** [comment]
It's the HSV values of the camera capture (mainly used for checking brightness), check out the code if you need more infos.
Also unless you really need the gesture system I suggest you look to another SmartMirror repository, this one is becoming quite old and others are a lot more community oriented than my simple personal project.
