### ISSUE TITLE
test.py error - ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by manuel0007** [Shinao/SmartMirror#12]
Hi, I would appriciate your help.
I tried to run the test.py file but i get the following error:

    __,contours,_ = cv2.findContours(search_hand_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
     ValueError: not enough values to unpack (expected 3, got 2)_

After i tried to change the 'Contours' (see below changes) i received the following error:

      _File "/home/pi/Downloads/SmartMirror-master/Motion/gesture.py", line 44, in CheckForPalm
      for i in range(self.defects.shape[1]):
      AttributeError: 'NoneType' object has no attribute 'shape'_

Changes '**Contours**':
------------------------------------------------------

        def InitFromMask(self, search_hand_mask):
        # Check each contours
        contours, _= cv2.findContours(search_hand_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

        for contour in contours:
            if self.InitFromContour(contour):
                return True
        return False

    def InitFromMaskAndPosition(self, search_hand_mask, nearestFromX, nearestfromY):
        # Check each contours
        contours, _= cv2.findContours(search_hand_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
        distanceContours = []`

**Comment by Shinao** [comment]
Hello there,

It seems that your OpenCV version is not the same than the one I used, and not returning the correct amount of values for the function. Which version are you using ?
Also this project of mine is becoming pretty old, there are now better community oriented project like this one on Github, if you didn't give them a try yet.

**Comment by manuel0007** [comment]
Hi,
I am proud to say that i  already found the fix :)
It was really because that my version is newer then what you developed.
What i did in my case was as follow:

Before:

     `def InitFromMask(self, search_hand_mask):
        # Check each contours
        (_, contours, _) = cv2.findContours(search_hand_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

        for contour in contours:
            if self.InitFromContour(contour):
                return True
        return False

    def InitFromMaskAndPosition(self, search_hand_mask, nearestFromX, nearestfromY):
        # Check each contours
        (_, contours, _) = cv2.findContours(search_hand_mask, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
        distanceContours = []`
Now:

     `def InitFromMask(self, search_hand_mask):
      # Check each contours
        contours = cv2.findContours(search_hand_mask.copy(), cv2.RETR_TREE, 
        cv2.CHAIN_APPROX_SIMPLE)[0]
        
        for contour in contours:
            if self.InitFromContour(contour):
                return True
        return False

    def InitFromMaskAndPosition(self, search_hand_mask, nearestFromX, nearestfromY):
        # Check each contours
        contours= cv2.findContours(search_hand_mask.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)[0]
        distanceContours = []`

Now i am stuck on tweaking HSV values so it will see my hand mask and that gesture will be recognize.
Still couldn't make it work.

**Comment by Shinao** [comment]
Make sure you run the debug version so that you can see what the camera capture and how the HSV values min/max takes from that capture, finally just tweak the value so all you get is your hands.

**Comment by manuel0007** [comment]
I tried but i can't get all gestures to be recognized :( it's taking long time.

**Comment by manuel0007** [comment]
Do you have any assumptions on why the debug work very very slowly (in your demo it working smooth and fast). ?

**Comment by Shinao** [comment]
I was using my PC and not the raspberry for the demo. Also make sure that your first gesture is a palm so that it can know where your hand is for your next gestures
