### ISSUE TITLE
Motion server issue

### ISSUE THREAD

**Issue by rudyv** [Shinao/SmartMirror#4]
Hi,

I managed to solve the first issue, thanks for your help, I now get the server up and running

When I try to run the python test.py command I also get into a nasty issue:

```
pi@raspberrypi3:~/SmartMirror/Motion $ python test.py
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from motion import Motion
  File "/home/pi/SmartMirror/Motion/motion.py", line 10, in <module>
    from picamera.array import PiRGBArray
ImportError: No module named picamera.array
```

Any suggestion on what might go wrong ?

**Comment by Shinao** [comment]
Hi,

Was the solution to the other issue the one I said so that I can update the repository ?
My bad, I added the possibility to use the pi camera in the config but didn't specified how to install the package in the README, I've added it :

> To use the Pi Camera set `piCamera` to true and install the package picamera `pip install "picamera[array]"`

Now comes the hard stuff, tweaking the settings so that it properly recognize your hand, enjoy :)
I will let this issue open a while so that we can have a follow-up.

**Comment by rudyv** [comment]
Bonjour Raphael,

The fitst Solution did work, so the server runs.
I'll try the suggestion for the camera in the coming days.
Kr,
Rudy

**Comment by rudyv** [comment]
Hi,

I did get a little bit further this evening. Still errors unfortunately
`pi@raspberrypi3:~/SmartMirror/Motion $ python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    import main
  File "/home/pi/SmartMirror/Motion/main.py", line 51, in <module>
    class CommandHandler(web.RequestHandler):
AttributeError: 'module' object has no attribute 'RequestHandler'
`
Any suggestion on this ?

**Comment by Shinao** [comment]
Sure, it sounds like you are missing the tornado package, as the README state : 

> pip install numpy
> pip install tornado

**Comment by rudyv** [comment]
Hi,

For both I get "requirement already satisfied"
So they are installed, any other suggestion ?

**Comment by Shinao** [comment]
Make sure you are using the latest version of python (3) not 2.7, pip and tornado.
