### ISSUE TITLE
How to use USB web camera 

### ISSUE THREAD

**Issue by mainframe2017** [Shinao/SmartMirror#5]
Please tell me how to use USB web camera instead of RPI On board camera as well as how view the screen on mirror instead of local web server.

Thank you

**Comment by Shinao** [comment]
> To use the Pi Camera set piCamera to true and install the package picamera pip install "picamera[array]"

By default it's already using the USB camera connected to your raspberry pi.
I don't get what you are trying to say after that but I would recommend to try and test things up on your home computer before tweaking the config directly on the mirror screen.

**Comment by mainframe2017** [comment]
I found this following issue during setup my palm.

![123](https://cloud.githubusercontent.com/assets/25217920/23705381/9bb3d4e2-042f-11e7-8c14-945fbac67dad.PNG)
![123234](https://cloud.githubusercontent.com/assets/25217920/23705382/9bb46100-042f-11e7-8c8d-09c9ee74ff76.PNG)

**Comment by Shinao** [comment]
For the second screenshots it seems it cannot find the key hsv_dec_blue from the config file. Did you change it by mistake maybe ?
For the first one it appears OpenCV failed on some function. Can't really know more without debugging.
What's your Python and OpenCV version ?

**Comment by mainframe2017** [comment]
I am using opencv2 and python 2.7

**Comment by Shinao** [comment]
I used Python 3 for this project and Open CV 2.7 if I remember correctly. Can you try with those version ?

**Comment by nitzjain** [comment]
Hello,

I am able to run the project but cannot use the picamera. It is not recognizing any hand gestures under many lighting changes. Also, I can select using a mouse. Do let me know where I am going wrong. Any help is appreciated. Thanks

**Comment by Shinao** [comment]
I need more details on this @nitzjain.
Is there a video feedback ? Did you try with an USB webcam ?
You speak of lighting changes, if you get to this point you have to tweak the settings as specified in the README for different lighting/color environment.

**Comment by nitzjain** [comment]
Hello Raphael,

Thank you for getting back to me so soon.
To answer your questions:
-I am using a PiCamera, attached directly on my raspberry pi3.(I tested the
camera with a simple python code to capture an image)
-I am able to run the npm start and node server.js commands. I am able to
see the start screen in the browser.
Now I cannot use the Picamera for gesture control. I tried changing the
config.py code : useCameraBoard': False, to useCameraBoard': True, but to
no use.

I would appreciate any help to be able to use the picamera for gesture
control.

Thanks
Nitesh Jain

**Comment by Shinao** [comment]
Did you install the picamera array module for python (see README) ?
Is there any error message displayed when you launch it ?

**Comment by nitzjain** [comment]
I checked everything again, still it doesn't work.
I have attached a screenshot of the installation.
There is no error when I run the web browser but for while running , I can
only use mouse pointer and not a gesture from picamera.

**Comment by Shinao** [comment]
The web browser app has nothing to do with the hand recognition feature. It only get messages from the python app that do track it. What happens when you launch the python program ?
Can't see your screenshot in your message.

**Comment by nitzjain** [comment]
![2017-03-31-075945_1280x800_scrot](https://cloud.githubusercontent.com/assets/26161161/24562202/d688ab16-15fe-11e7-9c7e-1306c361f4b0.png)

I hope you can view the screenshot now. After I run the command, I get "Server listening to port 3000" and I can see the magic mirror once I goto localhost:3000, but I cannot use the gesture feature.

**Comment by Shinao** [comment]
You have to run the python server to get the hand gesture recognition
`python test.py`
What do you get from that command ?

**Comment by dannysrouji** [comment]
Hello , my problem is my usb webcam works however it is too slow therefore cannot track my palm properly, is there anyway i could increase the cameras framerate per second?

**Comment by Shinao** [comment]
You could manually decrease the resolution and framerate in `config.py`.
If you are running `test.py` on your raspberry pi it is normal that it is stuttering : this debug program is really ressources intensive and is only to be used to setup your environment on your main computer to avoid the suffering of doing it on your pi. When the setup is complete you only have to launch `main.py`.

**Comment by dannysrouji** [comment]
thanks for the quick reply, what if i am using a usb webcam? config.py does not help me much in that case

**Comment by Shinao** [comment]
Indeed. In anyway I would suggest to test on your main PC and run on the pi when the setup is complete.

**Comment by dannysrouji** [comment]
Thanks again, i took your advice and kept receiving the following error (paramMinMaxPalm:13413): Gtk-WARNING **: cannot open display

**Comment by Shinao** [comment]
I need more infos on your errors. On what machine do you test it ? Are you launching test.py or setup.py ?
Please launch test.py on your main PC to try to setup before doing anything on the pi.

**Comment by dannysrouji** [comment]
on ubunto on a windows operating system , as well as I have tried it  on a mac terminal, I am launching test.py

**Comment by Shinao** [comment]
I used Python 3 for this project and Open CV 2.7 if I remember correctly. Are you using those ?

**Comment by dannysrouji** [comment]
Im using open cv 3.2.1, so my main question is how did you set up open CV on your PC for test.py?
as i keep recieving errors on that part

**Comment by Shinao** [comment]
I did not use this version because it was too new at the time. The 2.7 has many tutorials to install it on Linux and Windows. Can't really give you a step by step, you should try a different version or check if someone got the same errors as you on the OpenCV support board.

**Comment by dannysrouji** [comment]
Hello so i got everything to work, thank you so much for your help my problem is the enviroment, is it better to have a darker enviroment or  better lighting?, and also what are the ideal hsv values ?

**Comment by Shinao** [comment]
Nice !
Depends on the color of your skin. Your hand should not blend too much with your environment. White skin with a darker background/light and the opposite for black skin is what you should go with. Though if you adjust the HSV values just right it shouldn't matter since I tried to ignore the lightning condition and focus on the hand shape.
(The size of your hand is also a factor taken into account, make sure to tweak these settings too)

**Comment by dannysrouji** [comment]
thank you Raphael, so when i run test.py, after PALM is detected and
displayed several times, the server actually opens up , but does nothing
more for thumbs up..., however when i run main.py afterwards absolutely
nothing happens with the server, is there anything im missing?

**Comment by Shinao** [comment]
What do you mean the server : the browser ?
The only difference between `main.py` and `test.py` is that `test.py` will display a window where you can see your camera feedback with debug drawing on it. You then have to also run the nodejs server and launch your browser

**Comment by Shinao** [comment]
Closed due to inactivity.
