### ISSUE TITLE
How can i solve this problem?

### ISSUE THREAD

**Issue by seunghyuns** [Shinao/SmartMirror#6]
An error occurs like a picture.

Python version is version 2.7

Working with Documents

The Raspstill command works well with Picamera

Python does not recognize the camera
![kakaotalk_20170609_180242935](https://user-images.githubusercontent.com/28853157/26968720-05bd2df0-4d3e-11e7-9811-bd3bd5818e9a.jpg)
![kakaotalk_20170609_180243234](https://user-images.githubusercontent.com/28853157/26968731-10f416f2-4d3e-11e7-9f01-1a55c9454015.jpg)

**Comment by Shinao** [comment]
Hello,

First of all, it's tornado not torna~~r~~do that you need to install.

Then if you want to use the PiCamera : (from the README)
> config.py for the tracking settings
> To use the Pi Camera set piCamera to true and install the package picamera pip install "picamera[array]"

Also by using another version of python and/or OpenCV I can't really help if there is a problem :
> Software :
> OpenCV 2.x
> Python 3.x

**Comment by seunghyuns** [comment]
thank ; ) Shinao

you was told you to use Python 3, the basic Python version of the Raspberry Pi 3 was 2.7 version so I'm going to be able to get a fatal error by forcing you to upgrade the version 3.5, but Am i trying to run it like the "python3.5 command"? And when I installed OPENCV and run Python test.py, I had no import cv2

**Comment by Shinao** [comment]
I'm not sure I understand everything but if you install Python 3.x you have to install OpenCV correctly for this version. I know it can be a pain but I am not able to do a step by step installation guide, you should checkout some tutorials on how to properly configure Python3 with OpenCV.

**Comment by seunghyuns** [comment]
Thanks for the answer. would i format Raspberry Pi?  Would you like to follow the Python and OpenCV Install Guide in order to other websites that  have answered the other questions?
for example:
(this answer was yours)
Please follow this tutorial http://www.pyimagesearch.com/2015/03/30/accessing-the-raspberry-pi-camera-with-opencv-and-python/ from Step 4 through Step 5 to install the lib and tweak things if necessary. You also need to set the useRaspberryPiCamera to True in config.py.
but i will install python and opencv version :
Version of Python 3.5 
OpenCV version 2.7

**Comment by Shinao** [comment]
I have a really hard time understanding what you are writing.
I don't see how formatting the raspberry pi will help but only to clean the mess if there is one.
Also it's really not an issue with the SmartMirror but the environment its set in. I can only direct you to check out other great tutorials out there that have already done it and will explain it better than I do.
