### ISSUE TITLE
How can i solve this problem?

### ISSUE THREAD

**Issue by seunghyuns** [Shinao/SmartMirror#7]
![20170612151851](https://user-images.githubusercontent.com/28853157/27021362-bffa4a72-4f82-11e7-8971-b81f88b97258.png)

i saw this picture text (No camera found).

![2](https://user-images.githubusercontent.com/28853157/27021385-e620ad90-4f82-11e7-8bf9-7fc6edb99567.png)
This code works correctly

![1](https://user-images.githubusercontent.com/28853157/27021403-04e8741a-4f83-11e7-8c6d-26be2cbdc47e.png)

how can i replace VideoDevice code?

**Comment by Shinao** [comment]
> To use the Pi Camera set piCamera to true and install the package picamera pip install "picamera[array]"

Did you set **UseCameraBoard** to **true** in config.py ?

**Comment by seunghyuns** [comment]
The config.py has not changed anything
and i have installed pip picamera[array]

**Comment by Shinao** [comment]
You are going to have to debug a bit since I don't have this problem.
You could try commenting the line where its checking if the picamera is open.
From your code there is a time.sleep(0.1), maybe you should do the same in motion.py init() code so that the picamera have time to warmup.

**Comment by seunghyuns** [comment]
I really want to solve this problem captain

Why no camera found is being printed : <

First I'll fix the Usecamerboard code to true edit on config.py

**Comment by seunghyuns** [comment]
![20170613085901](https://user-images.githubusercontent.com/28853157/27060272-a76d460a-5016-11e7-94bd-f31a1ae33702.png)

LOL!! Finally Nocamerafound is not output.

But please help the camera screen is not output now


Thank you very much for each reply

**Comment by Shinao** [comment]
> 'Motion' object has no attribute 'picamera'

From your screenshot it appears you modified the code so I can't really help anymore, you have to fix it yourself by tweaking it a bit more. Clearly the part where the picamera is setup is not run so I would begin with that.

**Comment by seunghyuns** [comment]
thanks your oppinion

Can you tell where you installed  the OpenCV and the Python3 in website ?

2017-06-14 5:13 GMT+09:00 Raphael Monnerat <notifications@github.com>:

**Comment by Shinao** [comment]
I'm not sure what you mean. Where did I find how to in stall OpenCV and Py3 ? I do not remember it's been more than a year already. You are a bit on your own on that one I guess.
